In [1]:
import numpy as np

In [2]:
# IF YOU USE GOOGLE COLAB AND WANT READ A FILE
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
# Defining the examples used in these activity
toy_sentence_corpus = ['The cat sat on the mat',  'The dog chased the cat', 'The mat was soft and fluffy']

ShortCorpus=["my husband is sick", "call me sexist"]

MyCorpus = ["Yo it shirt he gave New York was funny.",
"my husband is sick, homemade chicken soup loading husband.",
"Witch raises wind to break up enemy’s lumber pound.",
"i got a new shirt at work at it is the WORST material ever",
"wave is so poor the girls can’t even dress up for Halloween",
"The theory of paint indicates feelings of isolation in society.",
"Wish sometimes I had access to the ever elusive cock carousel..",
"off probation tomorrow ima be a free woman again, FUCK THE SYSTEM"   ]

### EXAMPLE 1: Binary Bag of Word

In [4]:
#Bag of Word, considering binary vectors (binary=True)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
vectorizer.fit(MyCorpus)
X_bag_of_words = vectorizer.transform(MyCorpus)

#Print the computed vocabulary
print(vectorizer.vocabulary_)
print("Vocabulary size: ", len(vectorizer.vocabulary_))
for x in X_bag_of_words.toarray().astype(int):
	print(x)


{'yo': 65, 'it': 32, 'shirt': 45, 'he': 24, 'gave': 19, 'new': 37, 'york': 66, 'was': 57, 'funny': 18, 'my': 36, 'husband': 26, 'is': 30, 'sick': 46, 'homemade': 25, 'chicken': 7, 'soup': 50, 'loading': 33, 'witch': 61, 'raises': 44, 'wind': 59, 'to': 54, 'break': 4, 'up': 56, 'enemy': 11, 'lumber': 34, 'pound': 42, 'got': 21, 'at': 2, 'work': 63, 'the': 52, 'worst': 64, 'material': 35, 'ever': 13, 'wave': 58, 'so': 47, 'poor': 41, 'girls': 20, 'can': 5, 'even': 12, 'dress': 9, 'for': 15, 'halloween': 23, 'theory': 53, 'of': 38, 'paint': 40, 'indicates': 29, 'feelings': 14, 'isolation': 31, 'in': 28, 'society': 48, 'wish': 60, 'sometimes': 49, 'had': 22, 'access': 0, 'elusive': 10, 'cock': 8, 'carousel': 6, 'off': 39, 'probation': 43, 'tomorrow': 55, 'ima': 27, 'be': 3, 'free': 16, 'woman': 62, 'again': 1, 'fuck': 17, 'system': 51}
Vocabulary size:  67
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1

### EXAMPLE 2: Bag of Word without stopwords

In [5]:
#Bag of Word, considering the frequency of the terms (binary=False), and removing stopwords (stop_words="english")
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words="english", binary=False)
vectorizer.fit(MyCorpus)
X_bag_of_words = vectorizer.transform(MyCorpus)

#Print the computed vocabulary
print(vectorizer.vocabulary_)
print("Vocabulary size: ", len(vectorizer.vocabulary_))
for doc in X_bag_of_words.toarray().astype(int):
	print(doc)


{'yo': 43, 'shirt': 30, 'gave': 12, 'new': 24, 'york': 44, 'funny': 11, 'husband': 17, 'sick': 31, 'homemade': 16, 'chicken': 3, 'soup': 33, 'loading': 21, 'witch': 39, 'raises': 29, 'wind': 37, 'break': 1, 'enemy': 7, 'lumber': 22, 'pound': 27, 'got': 14, 'work': 41, 'worst': 42, 'material': 23, 'wave': 36, 'poor': 26, 'girls': 13, 'dress': 5, 'halloween': 15, 'theory': 34, 'paint': 25, 'indicates': 19, 'feelings': 8, 'isolation': 20, 'society': 32, 'wish': 38, 'access': 0, 'elusive': 6, 'cock': 4, 'carousel': 2, 'probation': 28, 'tomorrow': 35, 'ima': 18, 'free': 9, 'woman': 40, 'fuck': 10}
Vocabulary size:  45
[0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 1]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 1 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0]
[0 0 0 

### EXAMPLE 3: Bigrams of characters



In [6]:
#Bag of Word, considering the frequency of the bigrams of characters (binary=False)

ngram_vectorizer = CountVectorizer(analyzer='char_wb', ngram_range=(2, 2))
counts = ngram_vectorizer.fit_transform(ShortCorpus)
print(ngram_vectorizer.vocabulary_)
print("Vocabulary size: ", len(ngram_vectorizer.vocabulary_))
for x in counts.toarray().astype(int):
	print(x)



{' m': 3, 'my': 20, 'y ': 30, ' h': 1, 'hu': 13, 'us': 28, 'sb': 23, 'ba': 7, 'an': 6, 'nd': 21, 'd ': 10, ' i': 2, 'is': 15, 's ': 22, ' s': 4, 'si': 25, 'ic': 14, 'ck': 9, 'k ': 16, ' c': 0, 'ca': 8, 'al': 5, 'll': 18, 'l ': 17, 'me': 19, 'e ': 11, 'se': 24, 'ex': 12, 'xi': 29, 'st': 26, 't ': 27}
Vocabulary size:  31
[0 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1]
[1 0 0 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 1 1 0 1 0]


### EXAMPLE 4: 5-grams of characters

In [7]:
#Bag of Word, considering the frequency of the 5-grams of characters (binary=False)
ngram_vectorizer = CountVectorizer(analyzer='char_wb', ngram_range=(5, 5))
counts=ngram_vectorizer.fit_transform(ShortCorpus)
print(ngram_vectorizer.vocabulary_)
print("Vocabulary size: ", len(ngram_vectorizer.vocabulary_))
for doc in counts.toarray().astype(int):
   print(doc)

{' my ': 4, ' husb': 1, 'husba': 10, 'usban': 14, 'sband': 11, 'band ': 7, ' is ': 2, ' sick': 6, 'sick ': 13, ' call': 0, 'call ': 8, ' me ': 3, ' sexi': 5, 'sexis': 12, 'exist': 9, 'xist ': 15}
Vocabulary size:  16
[0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 0]
[1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 1]


### EXAMPLE 5: Bigrams of words

In [8]:
#Bag of Word, considering the frequency of the bigrams of words (binary=False), and removing stopwords (stop_words="english")
ngram_vectorizer = CountVectorizer(analyzer='word', ngram_range=(2,2), binary=False, stop_words="english")
data=ngram_vectorizer.fit_transform(MyCorpus)
print(ngram_vectorizer.vocabulary_)
print("Vocabulary size: ", len(ngram_vectorizer.vocabulary_))
for doc in data.toarray().astype(int):
   print(doc)

{'yo shirt': 38, 'shirt gave': 25, 'gave new': 9, 'new york': 20, 'york funny': 39, 'husband sick': 13, 'sick homemade': 27, 'homemade chicken': 12, 'chicken soup': 2, 'soup loading': 28, 'loading husband': 17, 'witch raises': 34, 'raises wind': 24, 'wind break': 32, 'break enemy': 1, 'enemy lumber': 6, 'lumber pound': 18, 'got new': 11, 'new shirt': 19, 'shirt work': 26, 'work worst': 36, 'worst material': 37, 'wave poor': 31, 'poor girls': 22, 'girls dress': 10, 'dress halloween': 4, 'theory paint': 29, 'paint indicates': 21, 'indicates feelings': 15, 'feelings isolation': 7, 'isolation society': 16, 'wish access': 33, 'access elusive': 0, 'elusive cock': 5, 'cock carousel': 3, 'probation tomorrow': 23, 'tomorrow ima': 30, 'ima free': 14, 'free woman': 8, 'woman fuck': 35}
Vocabulary size:  40
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 1]
[0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 0]
[0 1 0 0 0 0 1 0 0 0 0 0 0 

### Example 6: Unigrams of words with TF-IDF (using Pipeline)

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
import numpy as np

pipe = Pipeline([('count', CountVectorizer(stop_words="english", binary=False)), ('tfid', TfidfTransformer(use_idf=True))])
counts=pipe.fit_transform(MyCorpus)

print(pipe.named_steps['count'].vocabulary_)
for doc in counts.toarray():
   print(np.round(doc, 2))

{'yo': 43, 'shirt': 30, 'gave': 12, 'new': 24, 'york': 44, 'funny': 11, 'husband': 17, 'sick': 31, 'homemade': 16, 'chicken': 3, 'soup': 33, 'loading': 21, 'witch': 39, 'raises': 29, 'wind': 37, 'break': 1, 'enemy': 7, 'lumber': 22, 'pound': 27, 'got': 14, 'work': 41, 'worst': 42, 'material': 23, 'wave': 36, 'poor': 26, 'girls': 13, 'dress': 5, 'halloween': 15, 'theory': 34, 'paint': 25, 'indicates': 19, 'feelings': 8, 'isolation': 20, 'society': 32, 'wish': 38, 'access': 0, 'elusive': 6, 'cock': 4, 'carousel': 2, 'probation': 28, 'tomorrow': 35, 'ima': 18, 'free': 9, 'woman': 40, 'fuck': 10}
[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.43 0.43 0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.36 0.   0.   0.
 0.   0.   0.36 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.43 0.43]
[0.   0.   0.   0.33 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.33 0.67 0.   0.   0.   0.33 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.33 0.   0.33 0.   0.

### Example 6: Unigrams of words with TF-IDF

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words="english", binary=False, use_idf=True)
count=tfidf_vectorizer.fit_transform(MyCorpus)
print(tfidf_vectorizer.vocabulary_)
print("Vocabulary size: ", len(ngram_vectorizer.vocabulary_))
for doc in count.toarray():
   print(np.round(doc, 2))

{'yo': 43, 'shirt': 30, 'gave': 12, 'new': 24, 'york': 44, 'funny': 11, 'husband': 17, 'sick': 31, 'homemade': 16, 'chicken': 3, 'soup': 33, 'loading': 21, 'witch': 39, 'raises': 29, 'wind': 37, 'break': 1, 'enemy': 7, 'lumber': 22, 'pound': 27, 'got': 14, 'work': 41, 'worst': 42, 'material': 23, 'wave': 36, 'poor': 26, 'girls': 13, 'dress': 5, 'halloween': 15, 'theory': 34, 'paint': 25, 'indicates': 19, 'feelings': 8, 'isolation': 20, 'society': 32, 'wish': 38, 'access': 0, 'elusive': 6, 'cock': 4, 'carousel': 2, 'probation': 28, 'tomorrow': 35, 'ima': 18, 'free': 9, 'woman': 40, 'fuck': 10}
Vocabulary size:  40
[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.43 0.43 0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.36 0.   0.   0.
 0.   0.   0.36 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.43 0.43]
[0.   0.   0.   0.33 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.33 0.67 0.   0.   0.   0.33 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0

### Example 7: LSA document representation

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.decomposition import TruncatedSVD

#Document-Term Matrix
cv = CountVectorizer(stop_words="english", binary=False)
dtMatrix = cv.fit_transform(MyCorpus).toarray()
print("After building the document-term", dtMatrix.shape)
featurenames = cv.get_feature_names_out()
#print(featurenames)

#Tf-idf Transformation
tfidf = TfidfTransformer()
tfidfMatrix = tfidf.fit_transform(dtMatrix).toarray()
print("After building the TFIDF matrix", tfidfMatrix.shape)

#SVD
#n_components is recommended to be 100 by Sklearn Documentation for LSA
#http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html
svd = TruncatedSVD(n_components = 5)
svdMatrix = svd.fit_transform(tfidfMatrix)
print("After Transforming the vectorial space with LSA", svdMatrix.shape)
print(svdMatrix)

After building the document-term (8, 45)
After building the TFIDF matrix (8, 45)
After Transforming the vectorial space with LSA (8, 5)
[[ 7.93697112e-01 -2.52760702e-17  6.61962437e-18  2.73395866e-17
  -9.84027880e-18]
 [ 2.78003714e-16  1.62353547e-01 -3.20751236e-01 -1.74639092e-01
   6.01815585e-01]
 [-1.25706509e-16 -3.98466567e-01 -3.62191093e-01 -4.38472979e-01
   2.21896860e-01]
 [ 7.93697112e-01 -1.07454571e-16 -2.49865463e-16  3.47402277e-16
   3.83167894e-16]
 [-2.16864479e-16  5.90374040e-01 -4.78276370e-01 -2.62476217e-02
   1.83704208e-01]
 [-8.56159443e-17  5.36166939e-01  2.65075654e-01  3.37214885e-01
   1.52761243e-01]
 [ 9.50276324e-18 -2.05354950e-01  5.33951952e-01  5.54022143e-02
   7.14889506e-01]
 [-3.82554885e-16 -3.69700651e-01 -4.26401433e-01  8.12262527e-01
   1.42931962e-01]]
